sudo: required
language: java
jdk: openjdk8
services: postgresql
dist: trusty

## fix for buffer overflow https://github.com/travis-ci/travis-ci/issues/5227
addons:
  hostname: localhost

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -f  $HOME/.cache/pip/log/debug.log

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.cache/pip

before_install:
  - pip install --user codecov
  -

install:
  - ./gradlew compileJava compileTestJava assemble

before_script:
  - ls -la
  - find database/nakadi/10_data/ -type f -name "*.sql" | sort | while read -r filename; do psql -U postgres -a -f "$filename"; done
  - psql -c 'select * from zn_data.event_type' -U postgres

env:
  matrix:
    - TEST_SUITE="./gradlew acceptanceTest --stacktrace"

# run test suits in parallel
script: "$TEST_SUITE"
