sudo: required
language: java
jdk: openjdk8
services: postgresql
dist: trusty

## fix for buffer overflow https://github.com/travis-ci/travis-ci/issues/5227
addons:
  hostname: localhost
  postgresql: "9.6"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -f  $HOME/.cache/pip/log/debug.log

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.cache/pip

before_install:
  - pip install --user codecov
  -

install:
  - ./gradlew compileJava compileTestJava assemble

before_script:
  - ls -la
#  - find database/nakadi/10_data -type f -name "*.sql" | sort | while read -r filename; do psql -U postgres -a -f "$filename"; done
  - psql -c "CREATE ROLE nakadi PASSWORD 'nakadi' SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN;"
  - psql -c "CREATE DATABASE local_nakadi_db;"
  - psql -U nakadi local_nakadi_db -a -f "database/nakadi/10_data/00_create_schema.sql"
  - psql -U nakadi local_nakadi_db -a -f "database/nakadi/10_data/04_tables/01_event_type.sql"
  - psql -U nakadi local_nakadi_db -a -f "database/nakadi/10_data/04_tables/02_subscription.sql"
  - psql -U nakadi local_nakadi_db -a -f "database/nakadi/10_data/04_tables/03_event_type_schema.sql"
  - psql -U nakadi local_nakadi_db -a -f "database/nakadi/10_data/04_tables/04_storage.sql"
  - psql -U nakadi local_nakadi_db -a -f "database/nakadi/10_data/04_tables/05_timeline.sql"
  - wget http://www.us.apache.org/dist/kafka/0.9.0.1/kafka_2.11-0.9.0.1.tgz -O kafka.tgz
  - mkdir -p kafka && tar xzf kafka.tgz -C kafka --strip-components 1
  - nohup bash -c "cd kafka && bin/zookeeper-server-start.sh config/zookeeper.properties &"
  - nohup bash -c "cd kafka && bin/kafka-server-start.sh config/server.properties &"
  - sleep 5

env:
  matrix:
    - TEST_SUITE="./gradlew acceptanceTest --stacktrace"

# run test suits in parallel
script: "$TEST_SUITE"
