title: Nakadi Docs
baseurl: "nakadi/"
url: ""

collections:
  - documentation
  - api

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
