title: Nakadi
baseurl: "."
url: ""

collections:
  - documentation
  - api

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed

defaults:
  position: 1000
  method_order:
          - get
          - post
          - put
          - patch
          - delete
          - connect
          - head
          - options

